// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWOwp34h9yopmVzGhFbwIKYYYDZyw1ZA',
    appId: '1:284872657712:web:2aefb1f3c676dea2be16f5',
    messagingSenderId: '284872657712',
    projectId: 'food4need-f72b3',
    authDomain: 'food4need-f72b3.firebaseapp.com',
    storageBucket: 'food4need-f72b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3o3u5fRmq5F8Exheukkw_IVUBnEw6vk',
    appId: '1:284872657712:android:33e28207bb022d73be16f5',
    messagingSenderId: '284872657712',
    projectId: 'food4need-f72b3',
    storageBucket: 'food4need-f72b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtTYZwvJHX82DwSdkMWaoeT6IvL1uJ48',
    appId: '1:284872657712:ios:2e6973a438ec89c6be16f5',
    messagingSenderId: '284872657712',
    projectId: 'food4need-f72b3',
    storageBucket: 'food4need-f72b3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtTYZwvJHX82DwSdkMWaoeT6IvL1uJ48',
    appId: '1:284872657712:ios:2e6973a438ec89c6be16f5',
    messagingSenderId: '284872657712',
    projectId: 'food4need-f72b3',
    storageBucket: 'food4need-f72b3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABWOwp34h9yopmVzGhFbwIKYYYDZyw1ZA',
    appId: '1:284872657712:web:161357449645590cbe16f5',
    messagingSenderId: '284872657712',
    projectId: 'food4need-f72b3',
    authDomain: 'food4need-f72b3.firebaseapp.com',
    storageBucket: 'food4need-f72b3.firebasestorage.app',
  );
}
